# primary-setup/docker-compose.yml
version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: ${BROKER_ID}                             # Unique broker ID for each machine
      KAFKA_ZOOKEEPER_CONNECT: ${ZOOKEEPER_CONNECT}             # Zookeeper ensemble connection
      KAFKA_ADVERTISED_LISTENERS: INSIDE://localhost:9092,OUTSIDE://${NGROK_URL}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
