version: "3.8"
services:
  cassandra:
    build: .
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: "TestCluster"
      CASSANDRA_LISTEN_ADDRESS: "0.0.0.0"
      CASSANDRA_BROADCAST_ADDRESS: "cassandra"
      CASSANDRA_BROADCAST_RPC_ADDRESS: "cassandra"
      CASSANDRA_ENDPOINT_SNITCH: "SimpleSnitch"
      CASSANDRA_DC: dc1
      CASSANDRA_RACK: rack1
      CASSANDRA_SEEDS: cassandra
      CASSANDRA_START_RPC: true
    networks:
      - app_network

networks:
  app_network:
    external: true
