version: "3.8"
services:
  cassandra:
    build: .
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_DC: dc1
      CASSANDRA_RACK: rack1
      CASSANDRA_SEEDS: cassandra
      CASSANDRA_START_RPC: true
      CASSANDRA_LISTEN_ADDRESS: localhost
      CASSANDRA_BROADCAST_RPC_ADDRESS: 127.0.0.1
      CASSANDRA_RPC_ADDRESS: 0.0.0.0
    volumes:
      - ./db/data:/var/lib/cassandra/data
      - ./db/commitlog:/var/lib/cassandra/commitlog
      - ./db/hints:/var/lib/cassandra/hints
      - ./db/saved_caches:/var/lib/cassandra/saved_caches
      - ./db/logs:/var/log/cassandra
    networks:
      - app_network

networks:
  app_network:
    external: true
