# secondary-setup/docker-compose.yml
version: '3'
services:
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: ${BROKER_ID}                             # Unique broker ID
      KAFKA_ZOOKEEPER_CONNECT: ${ZOOKEEPER_CONNECT}             # Central Zookeeper ensemble
      KAFKA_ADVERTISED_LISTENERS: INSIDE://localhost:9092,OUTSIDE://${NGROK_URL}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
